import { StudioShell } from "@/components/StudioShell";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CalendarDays, CheckCircle2, ClipboardList, Gavel, GitPullRequest, Rocket, UsersRound } from "lucide-react";
import { Link } from "wouter";

const statusStyle: Record<string, string> = { draft: "bg-[#edf1e5] text-[#4f674c]", registration_open: "bg-[#fff2bd] text-[#7d6008]", hacking_active: "bg-[#e4f0e7] text-[#1b5e3a]", judging_active: "bg-[#e4ecf3] text-[#355d74]", completed: "bg-[#ececec] text-[#5e6462]" };
const journey = [
  { number: "01", title: "Design the challenge", detail: "Selected opportunity, sponsor, rules, tracks, prizes, rubric, and schedule.", icon: ClipboardList },
  { number: "02", title: "Mobilize teams", detail: "Registration, skill profiles, matching, join requests, mentors, and event updates.", icon: UsersRound },
  { number: "03", title: "Build the proof", detail: "Repositories, demos, videos, decks, technical checks, and original value indicators.", icon: GitPullRequest },
  { number: "04", title: "Judge the evidence", detail: "Hackathon Agent audit, assigned judge queue, rubric, citations, overrides, and objections.", icon: Gavel },
  { number: "05", title: "Realize the value", detail: "Leaderboard, investment gate, roadmap handoff, and consent-based learning.", icon: CheckCircle2 },
];

export default function HackathonBoard() {
  const { data: events, isLoading } = trpc.hackathons.list.useQuery();
  return <StudioShell eyebrow="Hackathon operating system"><section className="overflow-hidden border border-[#d7ddd0] bg-[#173d2a] text-[#f9f8f1]"><div className="grid gap-8 px-6 py-8 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#b6d0ae]">John Deere idea value studio</p><h1 className="mt-3 max-w-3xl font-serif text-[44px] leading-[.94]">A hackathon is no longer an event. <em className="font-normal text-[#ffd928]">It is a governed proof system.</em></h1><p className="mt-5 max-w-2xl text-[13px] leading-6 text-[#d0dfc9]">This is the operating center for the full journey: a sponsor-selected value case becomes a challenge; teams build evidence; the Hackathon Agent audits claims; people make the decision; the outcome returns to the investment portfolio.</p><Link href="/workspace" className="mt-6 inline-flex h-10 items-center gap-2 border border-[#9bbd93] px-4 text-[9px] font-bold uppercase tracking-[.12em] text-white hover:bg-[#244c35]">Find or select a challenge <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="border-t border-[#6f9671]/60 pt-5 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-0"><p className="text-[9px] font-bold uppercase tracking-[.15em] text-[#b6d0ae]">What this system runs</p><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-5"><div><dt className="font-serif text-[29px] text-[#ffd928]">{events?.length ?? 0}</dt><dd className="mt-1 text-[10px] leading-4 text-[#c9d8c4]">configured proof sprints</dd></div><div><dt className="font-serif text-[29px] text-[#ffd928]">5</dt><dd className="mt-1 text-[10px] leading-4 text-[#c9d8c4]">connected operating checkpoints</dd></div><div><dt className="font-serif text-[29px] text-[#ffd928]">1</dt><dd className="mt-1 text-[10px] leading-4 text-[#c9d8c4]">evidence trail from signal to decision</dd></div><div><dt className="font-serif text-[29px] text-[#ffd928]">0</dt><dd className="mt-1 text-[10px] leading-4 text-[#c9d8c4]">AI-only awards or investment decisions</dd></div></dl></div></div></section>
    <section className="mt-6 border-y border-[#d7ddd0] bg-[#f4f4ed] py-5"><div className="grid gap-4 xl:grid-cols-5">{journey.map((step, index) => { const Icon = step.icon; return <div key={step.number} className="relative px-2 xl:px-4"><div className="flex items-center gap-2"><span className="font-serif text-[20px] text-[#c89412]">{step.number}</span><Icon className="h-4 w-4 text-[#50704e]" /></div><h2 className="mt-2 text-[11px] font-bold text-[#1b3829]">{step.title}</h2><p className="mt-1 text-[10px] leading-4 text-[#6a756c]">{step.detail}</p>{index < journey.length - 1 && <i className="absolute right-0 top-3 hidden h-px w-3 bg-[#b4c3ae] xl:block" />}</div>; })}</div></section>
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#7a837b]">Challenge portfolio</p><h2 className="mt-1 font-serif text-[30px] text-[#1b3829]">Run the proof work in one place.</h2></div><div className="flex gap-3"><Link href="/submission-evidence" className="inline-flex h-9 items-center border border-[#cbd5c7] bg-white px-3 text-[9px] font-bold uppercase tracking-[.1em] text-[#45584a] hover:border-[#1b5e3a]">Participant submission</Link><Link href="/judging" className="inline-flex h-9 items-center bg-[#173d2a] px-3 text-[9px] font-bold uppercase tracking-[.1em] text-white hover:bg-[#0e2b1e]">Judge queue</Link></div></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{isLoading ? <p className="text-sm text-[#647066]">Loading configured hackathons…</p> : events?.length ? events.map(event => <Link key={event.id} href={`/hackathons/${event.id}`} className="group border border-[#d7ddd0] bg-[#fcfbf7] p-5 transition hover:-translate-y-0.5 hover:border-[#a8ba9e] hover:shadow-[0_16px_30px_rgba(37,57,44,.08)]"><div className="flex items-start justify-between gap-4"><span className={`h-fit px-2 py-1 text-[9px] font-bold uppercase tracking-[.12em] ${statusStyle[event.status]}`}>{event.status.replace("_", " ")}</span><span className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-[.11em] text-[#718076]">Open operating room <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span></div><h3 className="mt-5 font-serif text-[27px] leading-7 text-[#1b3829]">{event.title}</h3><p className="mt-2 text-[12px] leading-5 text-[#647066]">{event.tagline || event.description || "Evidence-led proof sprint"}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#e3e7df] pt-4 text-[10px] text-[#718076]"><span className="flex items-center gap-2"><CalendarDays className="h-3.5 w-3.5 text-[#1b5e3a]" />{event.hackingStart ? new Date(event.hackingStart).toLocaleDateString() : "Dates to configure"}</span><span className="text-right font-bold uppercase tracking-[.1em]">Teams · evidence · judges</span></div></Link>) : <div className="border border-dashed border-[#cfd8cb] bg-[#f8f9f4] p-10 text-center lg:col-span-2"><Rocket className="mx-auto h-8 w-8 text-[#95a38e]" /><p className="mt-3 font-serif text-[24px] text-[#2c4333]">No challenge is live yet.</p><p className="mx-auto mt-2 max-w-xl text-[12px] leading-5 text-[#718076]">Begin in the Value Field: capture the opportunity, research it, establish a value baseline, and let an authorized sponsor turn it into a challenge. The resulting proof sprint will appear here with its full operational lifecycle.</p><Link href="/workspace" className="mt-5 inline-flex h-9 items-center bg-[#173d2a] px-4 text-[9px] font-bold uppercase tracking-[.11em] text-white hover:bg-[#0e2b1e]">Open value field</Link></div>}</div></section></StudioShell>;
}
