import { StudioShell } from "@/components/StudioShell";
import { Button } from "@/components/ui/button";
import { EventConfigurationPanel } from "@/components/EventConfigurationPanel";
import { EventPulse } from "@/components/EventPulse";
import { HackathonLeaderboard } from "@/components/HackathonLeaderboard";
import { MentorRequestQueue } from "@/components/MentorRequestQueue";
import { OrganizerCopilotPanel } from "@/components/OrganizerCopilotPanel";
import { EventCommunicationsPanel } from "@/components/EventCommunicationsPanel";
import { EventStageGuide } from "@/components/EventStageGuide";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowLeft, ArrowRight, Bell, CircleDot, ClipboardCheck, Code2, Layers3, Rocket, UsersRound } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";

export default function HackathonDetail() {
  const [, params] = useRoute("/hackathons/:id");
  const hackathonId = Number(params?.id || 0);
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: governanceProfile } = trpc.governance.myProfile.useQuery();
  const { data, isLoading, error } = trpc.hackathons.detail.useQuery({ hackathonId }, { enabled: hackathonId > 0, refetchInterval: 15_000, refetchIntervalInBackground: false });
  const register = trpc.hackathons.register.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const createTeam = trpc.hackathons.createTeam.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const requestTeamJoin = trpc.hackathons.requestTeamJoin.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const createProject = trpc.hackathons.createProject.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const announce = trpc.hackathons.announce.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const status = trpc.hackathons.updateStatus.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  const [teamName, setTeamName] = useState("");
  const [projectTitle, setProjectTitle] = useState("");
  const [projectDescription, setProjectDescription] = useState("");
  const [githubUrl, setGithubUrl] = useState("");
  const [demoUrl, setDemoUrl] = useState("");
  const [videoUrl, setVideoUrl] = useState("");
  const [pitchDeckUrl, setPitchDeckUrl] = useState("");
  const [announcement, setAnnouncement] = useState("");
  const [announcementAudience, setAnnouncementAudience] = useState<"all" | "participants" | "judges" | "mentors">("all");

  if (isLoading) return <StudioShell eyebrow="Proof sprint"><p className="text-sm text-[#647066]">Opening the proof sprint…</p></StudioShell>;
  if (error || !data) return <StudioShell eyebrow="Proof sprint"><Link href="/hackathons" className="inline-flex items-center gap-2 text-[12px] font-bold text-[#1b5e3a]"><ArrowLeft className="h-4 w-4" />Return to proof sprints</Link><p className="mt-8 text-sm text-red-700">{error?.message || "Proof sprint not found."}</p></StudioShell>;
  const { event, tracks, rubric, teams, projects, announcements, faqs, schedule, myTeamIds, myLeaderTeamIds, myRegistrationRole } = data;
  const canAdminister = user?.role === "admin" || governanceProfile?.persona === "organizer" || governanceProfile?.persona === "sponsor";
  return <StudioShell eyebrow="Proof sprint workbench"><Link href="/hackathons" className="inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.12em] text-[#617064] hover:text-[#1b5e3a]"><ArrowLeft className="h-4 w-4" />All proof sprints</Link><section className="mt-5 border border-[#d7ddd0] bg-[#173d2a] p-6 text-[#f9f8f1] md:p-8"><div className="grid gap-7 xl:grid-cols-[1.25fr_.75fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#b6d0ae]">{event.status.replace("_", " ")}</p><h1 className="mt-2 font-serif text-[38px] leading-[.98]">{event.title}</h1><p className="mt-4 max-w-2xl text-[13px] leading-6 text-[#d0dfc9]">{event.description || "The selected opportunity’s evidence record frames this proof sprint."}</p></div><div className="border-t border-[#6f9671]/50 pt-5 xl:border-l xl:border-t-0 xl:pl-6 xl:pt-0"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#b6d0ae]">Judging posture</p><p className="mt-2 font-serif text-[25px] leading-7 text-[#ffd928]">Evidence first. Humans decide.</p><p className="mt-2 text-[11px] leading-5 text-[#d0dfc9]">The Hackathon Agent prepares citations, flags claim mismatches, and suggests a score. It cannot determine a winner.</p></div></div></section>
    {event.opportunityId && <section className="mt-5 flex flex-wrap items-center justify-between gap-4 border border-[#c9d4c7] bg-[#f0f1e7] px-5 py-4"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#4f674c]">Proof stage of the investment case</p><p className="mt-1 text-[12px] leading-5 text-[#526257]">This event is designed to test the originating value assumptions. It does not replace the sponsor’s economic case or investment gate.</p></div><Link href={`/opportunities/${event.opportunityId}`} className="inline-flex items-center gap-2 border border-[#1b5e3a] bg-[#fcfbf7] px-3 py-2 text-[9px] font-bold uppercase tracking-[.11em] text-[#1b5e3a] hover:bg-[#eaf2e7]">Open value case <ArrowRight className="h-3.5 w-3.5" /></Link></section>}
    <EventStageGuide hackathonId={hackathonId} opportunityId={event.opportunityId || null} status={event.status} projectId={projects[0]?.id || null} projectSubmitted={Boolean(projects[0]?.submittedAt)} canAdminister={canAdminister} registrationRole={myRegistrationRole} />
    <EventPulse hackathonId={hackathonId} />
    <span id="proof-design" className="block scroll-mt-6" />
    <span id="mobilize-proof" className="block scroll-mt-6" />
    <details className="mt-6 border border-[#cbd7c7] bg-[#f7f8f1]"><summary className="cursor-pointer px-5 py-4 text-[10px] font-bold uppercase tracking-[.13em] text-[#1b5e3a]">Open human-review ranking</summary><div className="border-t border-[#d7ddd0] px-5 pb-5"><HackathonLeaderboard hackathonId={hackathonId} /></div></details><section className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><article className="border border-[#d7ddd0] bg-[#fcfbf7] p-5"><div className="flex items-center gap-2 text-[#1b5e3a]"><Layers3 className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.15em]">Challenge tracks and rubric</p></div><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Prove the assumption that matters.</h2><div className="mt-5 space-y-3">{tracks.map(track => <div key={track.id} className="border-l-2 border-[#c89412] bg-[#fffdf2] p-3"><p className="text-[12px] font-bold text-[#304536]">{track.title}</p><p className="mt-1 text-[11px] leading-4 text-[#66746a]">{track.description}</p></div>)}</div><div className="mt-5 overflow-hidden border border-[#e0e4db]"><div className="grid grid-cols-[1fr_60px] bg-[#f4f4ed] px-3 py-2 text-[9px] font-bold uppercase tracking-[.12em] text-[#7f8980]"><span>Criterion</span><span>Weight</span></div>{rubric.map(item => <div key={item.id} className="grid grid-cols-[1fr_60px] border-t border-[#e5e8df] px-3 py-3"><span><b className="block text-[11px] text-[#314837]">{item.title}</b><small className="mt-0.5 block text-[10px] leading-4 text-[#748076]">{item.description}</small></span><strong className="text-[12px] text-[#1b5e3a]">{item.weight}%</strong></div>)}</div></article>
      <article className="border border-[#d7ddd0] bg-[#f0f1e7] p-5"><div className="flex items-center gap-2 text-[#4f674c]"><UsersRound className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.15em]">Join and form</p></div><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Assemble complementary proof.</h2><p className="mt-2 text-[12px] leading-5 text-[#647066]">Register first, then form a team around the selected evidence gap—not merely around an appealing prototype.</p><Button disabled={register.isPending} onClick={() => register.mutate({ hackathonId, role: "participant" })} className="mt-5 h-10 rounded-none bg-[#173d2a] text-[10px] font-bold uppercase tracking-[.12em] hover:bg-[#0e2b1e]">Register for this sprint</Button><div className="mt-5 border-t border-[#d7ddd0] pt-4"><label className="text-[9px] font-bold uppercase tracking-[.13em] text-[#758077]">Start a team<input value={teamName} onChange={event => setTeamName(event.target.value)} className="mt-2 h-10 w-full border border-[#cbd5c7] bg-white px-3 text-[12px] normal-case tracking-normal text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Team name" /></label><Button disabled={!teamName || createTeam.isPending} onClick={() => createTeam.mutate({ hackathonId, name: teamName, lookingForMembers: true })} variant="outline" className="mt-3 h-9 rounded-none border-[#1b5e3a] text-[10px] font-bold uppercase tracking-[.1em] text-[#1b5e3a]">Create team</Button></div><div className="mt-5 space-y-2">{teams.length ? teams.map(team => <div key={team.id} className="border border-[#d7ddd0] bg-white px-3 py-2"><div className="flex items-center justify-between gap-3"><span><b className="block text-[11px] text-[#314837]">{team.name}</b><small className="text-[9px] font-bold uppercase tracking-[.1em] text-[#758077]">{team.lookingForMembers ? "Open to members" : "Formed"}</small></span>{team.lookingForMembers && !myTeamIds.includes(team.id) && <Button disabled={requestTeamJoin.isPending} onClick={() => requestTeamJoin.mutate({ teamId: team.id })} variant="outline" className="h-7 rounded-none border-[#1b5e3a] text-[8px] font-bold uppercase tracking-[.1em] text-[#1b5e3a]">Request join</Button>}</div>{(canAdminister || myLeaderTeamIds.includes(team.id)) && <JoinRequestReview teamId={team.id} />}</div>) : <p className="text-[11px] text-[#758077]">No teams have formed yet.</p>}</div></article>
    </section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><article className="border border-[#d7ddd0] bg-[#fcfbf7] p-5"><div className="flex items-center gap-2 text-[#1b5e3a]"><Code2 className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.15em]">Submission workspace</p></div><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Submit the proof, not just the pitch.</h2><div className="mt-5 grid gap-3"><label className="text-[9px] font-bold uppercase tracking-[.13em] text-[#758077]">Project title<input value={projectTitle} onChange={event => setProjectTitle(event.target.value)} className="mt-2 h-10 w-full border border-[#cbd5c7] bg-white px-3 text-[12px] normal-case tracking-normal text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Proof project name" /></label><label className="text-[9px] font-bold uppercase tracking-[.13em] text-[#758077]">What did the team prove?<textarea value={projectDescription} onChange={event => setProjectDescription(event.target.value)} className="mt-2 min-h-24 w-full border border-[#cbd5c7] bg-white p-3 text-[12px] normal-case tracking-normal text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Describe the experiment, evidence, and remaining uncertainty." /></label><Button disabled={!projectTitle || projectDescription.length < 20 || createProject.isPending || !teams.length} onClick={() => createProject.mutate({ hackathonId, teamId: teams[0]?.id, trackId: tracks[0]?.id, title: projectTitle, description: projectDescription, techStack: [] })} className="h-10 rounded-none bg-[#173d2a] text-[10px] font-bold uppercase tracking-[.12em] hover:bg-[#0e2b1e]">Create draft submission</Button></div><div className="mt-5 border-t border-[#e2e6dd] pt-4">{projects.length ? projects.map(project => <div key={project.id} className="flex items-center justify-between gap-3 border-b border-[#e4e7e0] py-3 last:border-0"><span><b className="block text-[11px] text-[#314837]">{project.title}</b><small className="text-[10px] text-[#758077]">{project.submittedAt ? "Submitted" : "Draft"}</small></span><Link href={`/judging?project=${project.id}`} className="text-[10px] font-bold uppercase tracking-[.11em] text-[#1b5e3a]">Review evidence</Link></div>) : <p className="text-[11px] text-[#758077]">Project evidence will appear here after teams start submitting.</p>}</div></article>
      <article className="border border-[#d7ddd0] bg-[#f7f7f2] p-5"><div className="flex items-center gap-2 text-[#4f674c]"><Bell className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.15em]">Event operations</p></div><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Keep the sprint coordinated.</h2>{canAdminister && <div className="mt-5 border-y border-[#d7ddd0] py-4"><div className="flex flex-wrap gap-2"><Button onClick={() => status.mutate({ hackathonId, status: "registration_open" })} variant="outline" className="h-8 rounded-none text-[9px] font-bold uppercase tracking-[.1em]">Open registration</Button><Button onClick={() => status.mutate({ hackathonId, status: "hacking_active" })} variant="outline" className="h-8 rounded-none text-[9px] font-bold uppercase tracking-[.1em]">Start proof work</Button><Button onClick={() => status.mutate({ hackathonId, status: "judging_active" })} variant="outline" className="h-8 rounded-none text-[9px] font-bold uppercase tracking-[.1em]">Open judging</Button></div><select value={announcementAudience} onChange={event => setAnnouncementAudience(event.target.value as typeof announcementAudience)} className="mt-4 h-9 w-full border border-[#cbd5c7] bg-white px-3 text-[11px] text-[#1b3829]"><option value="all">All event members</option><option value="participants">Participants only</option><option value="judges">Judges only</option><option value="mentors">Mentors only</option></select><textarea value={announcement} onChange={event => setAnnouncement(event.target.value)} className="mt-3 min-h-20 w-full border border-[#cbd5c7] bg-white p-3 text-[12px] text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Post an organizer announcement" /><Button disabled={announcement.length < 3 || announce.isPending} onClick={() => announce.mutate({ hackathonId, title: "Organizer update", body: announcement, audience: announcementAudience })} className="mt-3 h-8 rounded-none bg-[#173d2a] text-[9px] font-bold uppercase tracking-[.1em] hover:bg-[#0e2b1e]">Post update</Button></div>}<div className="mt-5 space-y-3">{announcements.length ? announcements.map(item => <div key={item.id} className="border-l-2 border-[#c89412] bg-[#fffdf2] p-3"><p className="text-[11px] font-bold text-[#314837]">{item.title}</p><p className="mt-1 text-[11px] leading-4 text-[#66746a]">{item.body}</p></div>) : <p className="text-[11px] text-[#758077]">No announcements yet.</p>}</div></article>
    </section><EventCommunicationsPanel hackathonId={hackathonId} />{(canAdminister || myRegistrationRole === "mentor") && <MentorRequestQueue hackathonId={hackathonId} />}{canAdminister && <OrganizerCopilotPanel hackathonId={hackathonId} />}<details className="mt-6 border border-[#cbd7c7] bg-[#f7f8f1]"><summary className="cursor-pointer px-5 py-4 text-[10px] font-bold uppercase tracking-[.13em] text-[#1b5e3a]">Open additional organizer controls</summary><div className="border-t border-[#d7ddd0] px-5 pb-5"><TeamRecommendationPanel hackathonId={hackathonId} /><EventConfigurationPanel hackathonId={hackathonId} event={event} schedule={schedule} canAdminister={canAdminister} /><FaqPanel hackathonId={hackathonId} faqs={faqs} canAdminister={canAdminister} /></div></details></StudioShell>;
}

function JoinRequestReview({ teamId }: { teamId: number }) {
  const utils = trpc.useUtils();
  const { data: requests, isLoading } = trpc.hackathons.joinRequests.useQuery({ teamId });
  const decide = trpc.hackathons.decideJoinRequest.useMutation({ onSuccess: () => utils.hackathons.joinRequests.invalidate({ teamId }) });
  if (isLoading) return <p className="mt-2 text-[9px] text-[#758077]">Loading join requests…</p>;
  const pending = requests?.filter(request => request.status === "pending") || [];
  if (!pending.length) return <p className="mt-2 text-[9px] text-[#758077]">No pending join requests.</p>;
  return <div className="mt-3 border-t border-[#e2e6dd] pt-2"><p className="text-[8px] font-bold uppercase tracking-[.11em] text-[#758077]">Pending join requests</p>{pending.map(request => <div key={request.id} className="mt-2 flex items-center justify-between gap-2 text-[10px] text-[#617064]"><span>{request.message || "A participant requested to join."}</span><span className="flex shrink-0 gap-1"><Button disabled={decide.isPending} onClick={() => decide.mutate({ requestId: request.id, decision: "accepted" })} className="h-6 rounded-none bg-[#173d2a] px-2 text-[7px] font-bold uppercase">Accept</Button><Button disabled={decide.isPending} onClick={() => decide.mutate({ requestId: request.id, decision: "declined" })} variant="outline" className="h-6 rounded-none px-2 text-[7px] font-bold uppercase">Decline</Button></span></div>)}</div>;
}

function TeamRecommendationPanel({ hackathonId }: { hackathonId: number }) {
  const utils = trpc.useUtils();
  const { data, isLoading, error } = trpc.hackathons.suggestTeams.useQuery({ hackathonId });
  const request = trpc.hackathons.requestTeamJoin.useMutation({ onSuccess: () => utils.hackathons.suggestTeams.invalidate({ hackathonId }) });
  return <div className="mt-5 border-t border-[#d7ddd0] pt-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#758077]">Opt-in team suggestions</p><p className="mt-1 text-[10px] leading-4 text-[#647066]">Suggestions use only the skills and role availability you chose to share. They never assign you to a team.</p>{isLoading ? <p className="mt-3 text-[10px] text-[#758077]">Checking open-team fit…</p> : error ? <p className="mt-3 text-[10px] text-[#758077]">Register and opt in through your Talent Profile to see suggestions.</p> : data?.notice ? <p className="mt-3 text-[10px] text-[#758077]">{data.notice}</p> : <div className="mt-3 space-y-2">{data?.recommendations.map(team => <div key={team.teamId} className="border border-[#d7ddd0] bg-[#fffdf7] p-3"><div className="flex items-start justify-between gap-3"><div><b className="block text-[11px] text-[#314837]">{team.name}</b><p className="mt-1 text-[10px] leading-4 text-[#647066]">{team.reasons.join(" · ")}</p></div><Button disabled={request.isPending} onClick={() => request.mutate({ teamId: team.teamId, message: "Interested based on the opt-in team-fit suggestion." })} variant="outline" className="h-7 shrink-0 rounded-none border-[#1b5e3a] text-[8px] font-bold uppercase tracking-[.1em] text-[#1b5e3a]">Request join</Button></div></div>)}</div>}</div>;
}

function FaqPanel({ hackathonId, faqs, canAdminister }: { hackathonId: number; faqs: Array<{ id: number; question: string; answer: string }>; canAdminister: boolean }) {
  const utils = trpc.useUtils();
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const create = trpc.hackathons.createFaq.useMutation({ onSuccess: () => { setQuestion(""); setAnswer(""); utils.hackathons.detail.invalidate({ hackathonId }); } });
  const remove = trpc.hackathons.deleteFaq.useMutation({ onSuccess: () => utils.hackathons.detail.invalidate({ hackathonId }) });
  return <section className="mt-6 border border-[#d7ddd0] bg-[#f7f7f2] p-5"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#4f674c]">Event FAQ</p><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Make event guidance visible.</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{faqs.length ? faqs.map(faq => <div key={faq.id} className="border-l-2 border-[#c89412] bg-[#fffdf2] p-3"><p className="text-[11px] font-bold text-[#314837]">{faq.question}</p><p className="mt-1 text-[11px] leading-5 text-[#647066]">{faq.answer}</p>{canAdminister && <Button disabled={remove.isPending} onClick={() => remove.mutate({ faqId: faq.id })} variant="outline" className="mt-3 h-7 rounded-none border-[#914339] text-[8px] font-bold uppercase tracking-[.1em] text-[#914339]">Remove</Button>}</div>) : <p className="text-[11px] text-[#758077]">No event questions have been added yet.</p>}</div>{canAdminister && <div className="mt-5 border-t border-[#d7ddd0] pt-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#758077]">Add FAQ</p><input value={question} onChange={event => setQuestion(event.target.value)} className="mt-2 h-9 w-full border border-[#cbd5c7] bg-white px-3 text-[11px] text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Question" /><textarea value={answer} onChange={event => setAnswer(event.target.value)} className="mt-2 min-h-20 w-full border border-[#cbd5c7] bg-white p-3 text-[11px] text-[#1b3829] outline-none focus:border-[#1b5e3a]" placeholder="Answer" /><Button disabled={question.length < 5 || answer.length < 5 || create.isPending} onClick={() => create.mutate({ hackathonId, question, answer })} className="mt-3 h-9 rounded-none bg-[#173d2a] text-[9px] font-bold uppercase tracking-[.1em]">Add FAQ</Button></div>}</section>;
}
