import { useState } from "react";
import { BellRing, Check, Clock3, Loader2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export function communicationsUnavailableMessage(errorMessage?: string) {
  return errorMessage || "The event communication feed could not be loaded. No acknowledgement or team alert has been sent.";
}

export function EventCommunicationsPanel({ hackathonId }: { hackathonId: number }) {
  const utils = trpc.useUtils();
  const feed = trpc.hackathons.communicationsFeed.useQuery({ hackathonId }, { refetchInterval: 15_000, refetchIntervalInBackground: false });
  const [teamId, setTeamId] = useState("");
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const acknowledge = trpc.hackathons.acknowledgeAnnouncement.useMutation({ onSuccess: () => utils.hackathons.communicationsFeed.invalidate({ hackathonId }) });
  const alertTeam = trpc.hackathons.createTeamAlert.useMutation({ onSuccess: () => { setTeamId(""); setTitle(""); setBody(""); void utils.hackathons.communicationsFeed.invalidate({ hackathonId }); } });
  if (feed.isLoading) return <section className="mt-6 border border-[#d7ddd0] bg-[#f7f7f2] p-5"><p className="text-[11px] text-[#758077]">Loading the event communication feed…</p></section>;
  if (feed.error || !feed.data) return <section className="mt-6 border border-[#e5c9c3] bg-[#fff5f1] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#914339]">Acknowledged communications unavailable</p><p className="mt-2 text-[11px] leading-5 text-[#704b45]">{communicationsUnavailableMessage(feed.error?.message)}</p></div><Button onClick={() => void feed.refetch()} variant="outline" className="h-8 rounded-none border-[#914339] text-[8px] font-bold uppercase tracking-[.1em] text-[#914339]">Retry feed</Button></div></section>;
  return <section className="mt-6 border border-[#cbd7c7] bg-[#f0f4ed] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[#1b5e3a]"><BellRing className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.14em]">Acknowledged communications</p></div><h2 className="mt-2 font-serif text-[25px] text-[#1b3829]">Make event changes visible and traceable.</h2><p className="mt-2 max-w-2xl text-[11px] leading-5 text-[#536254]">Announcements are addressed to their intended audience. Recipients can confirm they received a change; team alerts route a specific schedule or evidence issue to one proof team.</p></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="space-y-3"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#4f674c]">Your addressed announcements</p>{feed.data.announcements.length ? feed.data.announcements.map(item => <article key={item.id} className="border border-[#d8e0d4] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#876e16]">{item.audience}</p><h3 className="mt-1 text-[13px] font-bold text-[#1b3829]">{item.title}</h3></div>{item.acknowledged ? <span className="inline-flex items-center gap-1 border border-[#b9d1b7] bg-[#edf5e9] px-2 py-1 text-[8px] font-bold uppercase tracking-[.09em] text-[#315e40]"><Check className="h-3 w-3" />Acknowledged</span> : <Button disabled={acknowledge.isPending} onClick={() => acknowledge.mutate({ announcementId: item.id })} variant="outline" className="h-7 rounded-none border-[#1b5e3a] text-[8px] font-bold uppercase tracking-[.09em] text-[#1b5e3a]">Confirm receipt</Button>}</div><p className="mt-2 text-[11px] leading-5 text-[#536254]">{item.body}</p>{feed.data.isOrganizer && <p className="mt-2 text-[9px] uppercase tracking-[.08em] text-[#758077]">{item.acknowledgementCount} acknowledgement{item.acknowledgementCount === 1 ? "" : "s"}</p>}</article>) : <p className="border border-dashed border-[#cbd7c7] bg-white p-4 text-[11px] text-[#758077]">No announcements are currently addressed to this event role.</p>}</div>
      <aside className="border border-[#d8e0d4] bg-[#fffef9] p-4"><div className="flex items-center gap-2 text-[#4f674c]"><Clock3 className="h-4 w-4" /><p className="text-[9px] font-bold uppercase tracking-[.12em]">Event timeline</p></div><div className="mt-3 space-y-3">{feed.data.timeline.slice(0, 10).map(item => <div key={item.id} className="border-l-2 border-[#c89412] pl-3"><p className="text-[9px] font-bold uppercase tracking-[.09em] text-[#758077]">{item.type.replace("_", " ")} · {new Date(item.occurredAt).toLocaleString()}</p><p className="mt-1 text-[11px] font-bold text-[#1b3829]">{item.title}</p><p className="mt-1 text-[10px] leading-4 text-[#647066]">{item.detail}</p></div>)}{!feed.data.timeline.length && <p className="text-[11px] text-[#758077]">The timeline will include announcements, office hours, deadlines, and team alerts as they are recorded.</p>}</div></aside></div>
    {feed.data.isOrganizer && <div className="mt-5 border-t border-[#cbd8c7] pt-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#1b5e3a]">Team-scoped alert</p><div className="mt-3 grid gap-3 md:grid-cols-[180px_1fr]"><select value={teamId} onChange={event => setTeamId(event.target.value)} className="h-10 border border-[#cbd5c7] bg-white px-3 text-[11px] text-[#1b3829]"><option value="">Select a proof team</option>{feed.data.teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select><input value={title} onChange={event => setTitle(event.target.value)} className="h-10 border border-[#cbd5c7] bg-white px-3 text-[11px] text-[#1b3829]" placeholder="Alert title" /></div><textarea value={body} onChange={event => setBody(event.target.value)} className="mt-3 min-h-20 w-full border border-[#cbd5c7] bg-white p-3 text-[11px] text-[#1b3829]" placeholder="Describe the schedule or evidence issue for this team." /><Button disabled={!teamId || title.length < 3 || body.length < 3 || alertTeam.isPending} onClick={() => alertTeam.mutate({ hackathonId, teamId: Number(teamId), title, body })} className="mt-3 h-8 rounded-none bg-[#173d2a] text-[8px] font-bold uppercase tracking-[.1em]">{alertTeam.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <><Send className="mr-1 h-3 w-3" />Send team alert</>}</Button>{alertTeam.error && <p className="mt-2 text-[10px] text-red-700">{alertTeam.error.message}</p>}</div>}
  </section>;
}
