export function ExecutiveHeatMapCallout({ executiveHeatMap }: { executiveHeatMap: unknown }) {
  const dimensions = executiveHeatMap && typeof executiveHeatMap === "object" && Array.isArray((executiveHeatMap as { dimensions?: unknown }).dimensions)
    ? (executiveHeatMap as { dimensions: Array<{ key?: unknown; label?: unknown; score?: unknown }> }).dimensions.filter(item => typeof item.label === "string" && typeof item.score === "number")
    : [];

  if (!dimensions.length) return null;

  return (
    <section className="mt-6 border border-[#c7d6c3] bg-[#eef4e9] p-5">
      <p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#55705b]">Human executive heat-map assessment</p>
      <h3 className="mt-1 font-serif text-2xl text-[#173d2a]">Value, skill, and will recorded with the proof.</h3>
      <p className="mt-2 text-sm leading-6 text-[#556557]">These ratings were entered by a human judge after review. They are not generated by the Agent and do not replace the sponsor investment gate.</p>
      <div className="mt-4 grid gap-px border border-[#cbd6c8] bg-[#cbd6c8] sm:grid-cols-4">
        {dimensions.map(item => <div key={String(item.key || item.label)} className="bg-white p-3"><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#657366]">{String(item.label)}</p><p className="mt-1 font-serif text-2xl text-[#173d2a]">{Number(item.score).toFixed(1)}<span className="ml-1 text-xs text-[#657366]">/5</span></p></div>)}
      </div>
    </section>
  );
}
