import { useEffect, useState } from "react";
import { Bot, CheckCircle2, FileSearch, Loader2, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type TrackDraft = { title: string; description: string; sourceLabels: string[] };
type RubricDraft = { title: string; description: string; evaluationMethod: string; suggestedWeight: number; sourceLabels: string[] };
type CopilotPayload = { tracks?: TrackDraft[]; rubric?: RubricDraft[]; requiredEvidence?: Array<{ item: string; sourceLabels: string[] }>; proofQuestions?: Array<{ question: string; sourceLabels: string[] }>; limitations?: string[] };
type EditableTrack = { title: string; description: string };
type EditableRubric = { title: string; description: string; evaluationMethod: string; weight: number };

function payloadOf(value: unknown): CopilotPayload {
  return value && typeof value === "object" && !Array.isArray(value) ? value as CopilotPayload : {};
}

export function OrganizerCopilotPanel({ hackathonId }: { hackathonId: number }) {
  const utils = trpc.useUtils();
  const drafts = trpc.hackathons.organizerCopilotDrafts.useQuery({ hackathonId }, { refetchInterval: 20_000, refetchIntervalInBackground: false });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [tracks, setTracks] = useState<EditableTrack[]>([]);
  const [rubric, setRubric] = useState<EditableRubric[]>([]);
  const create = trpc.hackathons.draftFromOpportunity.useMutation({ onSuccess: result => { setSelectedId(result.draftId); setTracks(result.payload.tracks.map(item => ({ title: item.title, description: item.description }))); setRubric(result.payload.rubric.map(item => ({ title: item.title, description: item.description, evaluationMethod: item.evaluationMethod, weight: item.suggestedWeight }))); void utils.hackathons.organizerCopilotDrafts.invalidate({ hackathonId }); } });
  const adopt = trpc.hackathons.adoptOrganizerCopilotDraft.useMutation({ onSuccess: () => { void utils.hackathons.organizerCopilotDrafts.invalidate({ hackathonId }); void utils.hackathons.detail.invalidate({ hackathonId }); } });
  const selected = drafts.data?.find(draft => draft.id === selectedId) || drafts.data?.[0] || null;
  const payload = payloadOf(selected?.payload);
  useEffect(() => {
    if (!selected || selected.id === selectedId && tracks.length) return;
    setSelectedId(selected.id);
    setTracks((payload.tracks || []).map(item => ({ title: item.title, description: item.description })));
    setRubric((payload.rubric || []).map(item => ({ title: item.title, description: item.description, evaluationMethod: item.evaluationMethod, weight: item.suggestedWeight })));
  }, [selected?.id, drafts.data]);
  const canAdopt = selected?.status === "draft" && tracks.length > 0 && rubric.length > 0 && rubric.every(item => item.weight > 0);
  return <section className="mt-6 border border-[#c7d7c4] bg-[#edf3e9] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[#1b5e3a]"><Bot className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.15em]">Organizer copilot</p></div><h2 className="mt-2 font-serif text-[27px] text-[#1b3829]">Turn cited opportunity evidence into an editable proof design.</h2><p className="mt-2 max-w-3xl text-[12px] leading-5 text-[#536254]">The copilot drafts tracks, proof criteria, evidence requirements, and questions from the selected opportunity. It never publishes configuration, creates economics, selects winners, or changes a human decision.</p></div><Button disabled={create.isPending} onClick={() => create.mutate({ hackathonId })} className="h-10 rounded-none bg-[#173d2a] text-[9px] font-bold uppercase tracking-[.11em] hover:bg-[#0e2b1e]">{create.isPending ? <><Loader2 className="mr-2 h-3 w-3 animate-spin" />Drafting from evidence…</> : <><Sparkles className="mr-2 h-3 w-3" />Draft from opportunity evidence</>}</Button></div>
    <span id="organizer-copilot" className="block scroll-mt-6" />
    {create.error && <p className="mt-3 text-[11px] text-red-700">{create.error.message}</p>}
    {drafts.isLoading ? <p className="mt-5 text-[11px] text-[#758077]">Loading retained draft history…</p> : !selected ? <p className="mt-5 border border-dashed border-[#bfd0bc] bg-white p-4 text-[11px] leading-5 text-[#647066]">No draft has been created. Start with the opportunity evidence when you are ready to prepare an editable event design.</p> : <><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-y border-[#cbd8c7] py-3"><div className="flex flex-wrap gap-2">{drafts.data?.map(draft => <button key={draft.id} onClick={() => { const next = payloadOf(draft.payload); setSelectedId(draft.id); setTracks((next.tracks || []).map(item => ({ title: item.title, description: item.description }))); setRubric((next.rubric || []).map(item => ({ title: item.title, description: item.description, evaluationMethod: item.evaluationMethod, weight: item.suggestedWeight }))); }} className={`border px-2 py-1 text-[9px] font-bold uppercase tracking-[.09em] ${draft.id === selected.id ? "border-[#1b5e3a] bg-[#173d2a] text-white" : "border-[#cbd5c7] bg-white text-[#526257]"}`}>Draft {draft.id} · {draft.status}</button>)}</div><p className="text-[10px] text-[#647066]">Draft provenance is retained. All items start unadopted.</p></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-5"><div className="border border-[#d4dfd0] bg-white p-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#1b5e3a]">Editable tracks</p><div className="mt-3 space-y-3">{tracks.map((track, index) => <div key={`${selected.id}-track-${index}`} className="border border-[#e1e7df] p-3"><input value={track.title} onChange={event => setTracks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} className="h-8 w-full border-b border-[#cbd5c7] bg-transparent text-[12px] font-bold text-[#1b3829] outline-none focus:border-[#1b5e3a]" /><textarea value={track.description} onChange={event => setTracks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} className="mt-2 min-h-16 w-full bg-transparent text-[11px] leading-4 text-[#536254] outline-none" />{payload.tracks?.[index]?.sourceLabels?.length ? <p className="mt-2 text-[9px] uppercase tracking-[.08em] text-[#738174]">Evidence labels: {payload.tracks[index].sourceLabels.join(" · ")}</p> : null}</div>)}</div><Button onClick={() => setTracks(current => [...current, { title: "New track", description: "Describe the proof goal." }])} variant="outline" className="mt-3 h-8 rounded-none border-[#1b5e3a] text-[8px] font-bold uppercase tracking-[.1em] text-[#1b5e3a]"><Plus className="mr-1 h-3 w-3" />Add track</Button></div>
        <div className="border border-[#d4dfd0] bg-white p-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#1b5e3a]">Editable human rubric</p><div className="mt-3 space-y-3">{rubric.map((item, index) => <div key={`${selected.id}-rubric-${index}`} className="border border-[#e1e7df] p-3"><div className="grid gap-2 sm:grid-cols-[1fr_84px]"><input value={item.title} onChange={event => setRubric(current => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, title: event.target.value } : entry))} className="h-8 border-b border-[#cbd5c7] bg-transparent text-[12px] font-bold text-[#1b3829] outline-none focus:border-[#1b5e3a]" /><input type="number" min="1" max="100" value={item.weight} onChange={event => setRubric(current => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, weight: Number(event.target.value) } : entry))} className="h-8 border border-[#cbd5c7] px-2 text-[11px] text-[#1b3829]" /></div><textarea value={item.description} onChange={event => setRubric(current => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, description: event.target.value } : entry))} className="mt-2 min-h-14 w-full bg-transparent text-[11px] leading-4 text-[#536254] outline-none" /><input value={item.evaluationMethod} onChange={event => setRubric(current => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, evaluationMethod: event.target.value } : entry))} className="mt-2 h-7 w-full border-t border-[#e4e9e2] bg-transparent text-[10px] text-[#647066] outline-none" placeholder="Human evaluation method" />{payload.rubric?.[index]?.sourceLabels?.length ? <p className="mt-2 text-[9px] uppercase tracking-[.08em] text-[#738174]">Evidence labels: {payload.rubric[index].sourceLabels.join(" · ")}</p> : null}</div>)}</div></div></div>
        <aside className="space-y-4"><div className="border border-[#d4dfd0] bg-[#fffef9] p-4"><div className="flex items-center gap-2 text-[#4f674c]"><FileSearch className="h-4 w-4" /><p className="text-[9px] font-bold uppercase tracking-[.13em]">Proof requirements</p></div><ul className="mt-3 space-y-2 text-[11px] leading-4 text-[#536254]">{payload.requiredEvidence?.map((item, index) => <li key={index}><span className="font-semibold text-[#1b3829]">{item.item}</span><br /><span className="text-[9px] uppercase tracking-[.08em] text-[#758077]">{item.sourceLabels.join(" · ")}</span></li>)}</ul></div><div className="border border-[#d4dfd0] bg-[#fffef9] p-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#4f674c]">Questions to prove</p><ul className="mt-3 space-y-2 text-[11px] leading-4 text-[#536254]">{payload.proofQuestions?.map((item, index) => <li key={index}>{item.question}<br /><span className="text-[9px] uppercase tracking-[.08em] text-[#758077]">{item.sourceLabels.join(" · ")}</span></li>)}</ul></div><div className="border border-[#eadcb4] bg-[#fff9e9] p-4"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#876e16]">Draft limitations</p><ul className="mt-3 space-y-2 text-[11px] leading-4 text-[#665e43]">{payload.limitations?.map((item, index) => <li key={index}>{item}</li>)}</ul></div></aside></div>
      <div className="mt-5 border-t border-[#cbd8c7] pt-4"><Button disabled={!canAdopt || adopt.isPending} onClick={() => selected && adopt.mutate({ draftId: selected.id, tracks, rubric })} className="h-10 rounded-none bg-[#173d2a] text-[9px] font-bold uppercase tracking-[.11em] hover:bg-[#0e2b1e]">{adopt.isPending ? <><Loader2 className="mr-2 h-3 w-3 animate-spin" />Adopting configuration…</> : <><CheckCircle2 className="mr-2 h-3 w-3" />Explicitly adopt edited tracks and rubric</>}</Button>{selected.status === "adopted" && <p className="mt-3 text-[11px] text-[#315e40]">This retained draft was adopted. Create a new draft for another configuration change.</p>}{adopt.error && <p className="mt-3 text-[11px] text-red-700">{adopt.error.message}</p>}</div></>}
  </section>;
}
