import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { SearchCode } from "lucide-react";
import { useState } from "react";

export function RepositorySearchPanel({ projectId }: { projectId: number }) {
  const [draft, setDraft] = useState("");
  const [query, setQuery] = useState("");
  const evidence = trpc.repositories.searchIndexedEvidence.useQuery({ projectId, query: query || "pending", limit: 5 }, { enabled: query.length >= 3 });
  return <article className="mt-6 border border-[#d7ddd0] bg-[#fcfbf7] p-5"><div className="flex items-center gap-2 text-[#1b5e3a]"><SearchCode className="h-4 w-4" /><p className="text-[10px] font-bold uppercase tracking-[.14em]">Indexed code evidence</p></div><h2 className="mt-2 font-serif text-[24px] text-[#1b3829]">Ask the approved proof—not the whole internet.</h2><p className="mt-2 max-w-2xl text-[11px] leading-5 text-[#647066]">Searches run only against bounded commit diffs from the currently authorized repository. Results retain their file path and commit provenance; revoked repositories are not searchable.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && draft.trim().length >= 3) setQuery(draft.trim()); }} className="h-10 flex-1 border border-[#cbd5c7] bg-white px-3 text-[12px] text-[#1b3829]" placeholder="e.g., telemetry validation, evidence route, commit audit" /><Button disabled={draft.trim().length < 3} onClick={() => setQuery(draft.trim())} className="h-10 rounded-none bg-[#173d2a] text-[9px] font-bold uppercase tracking-[.1em]">Search indexed evidence</Button></div>{evidence.isLoading && <p className="mt-4 text-[11px] text-[#758077]">Searching authorized code evidence…</p>}{evidence.error && <p className="mt-4 text-[11px] text-[#9c3d2f]">{evidence.error.message}</p>}{evidence.data?.length ? <div className="mt-4 space-y-3">{evidence.data.map(result => <div key={result.id} className="border border-[#d7ddd0] bg-[#f5f6ef] p-3"><div className="flex flex-wrap justify-between gap-2"><b className="font-mono text-[10px] text-[#314837]">{result.filePath}</b><span className="text-[9px] uppercase tracking-[.1em] text-[#758077]">commit {result.commitSha.slice(0, 10)} · relevance {Math.round(result.similarity * 100)}%</span></div><pre className="mt-2 max-h-36 overflow-auto whitespace-pre-wrap text-[10px] leading-4 text-[#526159]">{result.contentChunk.slice(0, 1200)}</pre></div>)}</div> : query && !evidence.isLoading && !evidence.error ? <p className="mt-4 text-[11px] text-[#758077]">No indexed commit evidence matched. Run the approved repository monitor after a new commit is available.</p> : null}</article>;
}
